modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hermitpurple"
version = "${version}"
displayName = "JCraft Hermit Purple Addon"
authors = "Arsik"
description = '''
Adds the stand of Joseph Joestar, Hermit Purple, into JCraft!
'''
logoFile = "assets/hermitpurple/icon.png"

[[dependencies.hermitpurple]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hermitpurple]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hermitpurple]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hermitpurple]]
modId = "jcraft"
mandatory = true
versionRange = "[0.18.0,)"
ordering = "AFTER"
side = "BOTH"
